let state;
let current = 'richard';
const $ = (s) => document.querySelector(s);
const eur = (n) => new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(n);
async function api(path, body) { const r=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const p=await r.json(); if(!r.ok) throw Error(p.error); return p; }
function notice(t,bad=false){ $('#notice').innerHTML='<div class="notice '+(bad?'error':'')+'">'+t+'</div>'; }
async function refresh(){ const r=await fetch('/api/state?actorId='+encodeURIComponent(current)); state=await r.json(); if(!r.ok) throw Error(state.error); render(); }
function hideForEmployee(){ ['stats','projects','manager','link'].forEach(id=>{const el=$('#'+id); if(el) el.closest('section')?.classList.add('hidden');}); }
function render(){ const me=state.employees.find(p=>p.id===current); const manager=me.role==='manager'; $('#role').innerHTML=state.employees.map(p=>'<option value="'+p.id+'" '+(p.id===current?'selected':'')+'>'+p.name+'</option>').join(''); $('#saleForm').classList.toggle('hidden',me.role!=='sales'); $('#expenseForm').classList.toggle('hidden',me.role!=='expense'); if(!manager) hideForEmployee(); else { const t=state.totals; $('#stats').innerHTML='<div class="stat"><span class="muted">Company result</span><b>'+eur(t.company)+'</b></div>'; } renderManager(manager); renderTable(manager); }
function renderManager(manager){ if(!manager){ $('#manager').innerHTML=''; return; } const pending=state.records.filter(r=>r.status==='pending_approval'||r.status==='awaiting_allocation'); $('#manager').innerHTML='<h2>Manager decisions</h2>'+(pending.length?'':'<div class="notice">No decisions awaiting action.</div>'); }
function renderTable(manager){ const rows=state.records.slice().reverse().map(r=>'<tr><td><b>'+r.reference+'</b></td><td>'+r.type+'</td><td>'+r.description+'</td><td>'+eur(r.amount)+'</td><td><span class="tag">'+r.status.replaceAll('_',' ')+'</span>'+(manager?'<br><span class="muted">Sheets: '+r.syncStatus+' / Telegram: '+r.notificationStatus+'</span>':'')+'</td></tr>').join(''); $('#table').innerHTML='<table><thead><tr><th>Reference</th><th>Type</th><th>Description</th><th>Amount</th><th>Status</th></tr></thead><tbody>'+ (rows||'<tr><td colspan="5">No submissions yet.</td></tr>')+'</tbody></table>'; }
$('#role').addEventListener('change',async e=>{current=e.target.value; try{await refresh();}catch(x){notice(x.message,true);}});
$('#saleForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/submit',{actorId:current,record:{type:'sale',reference:f.get('reference'),customer:f.get('customer'),description:f.get('description'),project:f.get('project'),amount:f.get('amount'),shares:{richard:Number(f.get('richard')),anastasia:Number(f.get('anastasia')),jean:Number(f.get('jean'))}}});e.target.reset();notice('Sale saved.');await refresh();}catch(x){notice(x.message,true);}});
$('#expenseForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{await api('/api/submit',{actorId:current,record:{type:'expense',reference:f.get('reference'),description:f.get('description'),category:f.get('category'),amount:f.get('amount'),proposedAllocation:f.get('allocation')}});e.target.reset();notice('Expense saved.');await refresh();}catch(x){notice(x.message,true);}});
refresh().catch(x=>notice(x.message,true));
